// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getAll
DataFrame getAll(const std::string& path);
RcppExport SEXP RcppGetconf_getAll(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    __result = Rcpp::wrap(getAll(path));
    return __result;
END_RCPP
}
// getConfig
SEXP getConfig(const std::string& var, const std::string& path);
RcppExport SEXP RcppGetconf_getConfig(SEXP varSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const std::string& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    __result = Rcpp::wrap(getConfig(var, path));
    return __result;
END_RCPP
}
